/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package advancedhangman;

/**
 *
 * @author Justin
 * 
 */
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;

public class View extends javax.swing.JFrame {

    JButton [] letterbuttons = new JButton[26];
    String username, password,password22;
    Graphics2D gfx; 
    
    
    /**
     * Creates new form View
     */
    public View() {
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((screen.getWidth() - getWidth()) /4);
        int y = (int) ((screen.getHeight() -getHeight()) /4);
        setLocation(x, y);

        initComponents();
        output.setEditable(false);
        
        jTabbedPane2.setVisible(false);
        letterpanel.setVisible(false);
        
        openingdialog.setTitle("Welcome");
        openingdialog.setLocationRelativeTo(null);
        openingdialog.pack();
        openingdialog.setVisible(true);
        
        
        letterpanel.setLayout(new java.awt.GridLayout(4, 7, 10, 10));
        genLetters();
        addLetters();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        openingdialog = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        registerbutton = new javax.swing.JButton();
        loginbutton = new javax.swing.JButton();
        logindialog = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        password1 = new javax.swing.JPasswordField();
        username1 = new javax.swing.JTextField();
        loginconfirm = new javax.swing.JButton();
        registerdialog = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        username2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        registerconfirm = new javax.swing.JButton();
        password2 = new javax.swing.JPasswordField();
        password3 = new javax.swing.JPasswordField();
        difficultydialog = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        easy = new javax.swing.JButton();
        medium = new javax.swing.JButton();
        hard = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        output = new javax.swing.JTextField();
        newgamebutton = new javax.swing.JButton();
        selectdifficultybutton = new javax.swing.JButton();
        winlosslabel = new javax.swing.JLabel();
        drawingpanel = new javax.swing.JPanel();
        userinfo = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        deleteAccountButton = new javax.swing.JButton();
        letterpanel = new javax.swing.JPanel();

        openingdialog.setBackground(new java.awt.Color(0, 0, 128));

        jLabel1.setBackground(new java.awt.Color(0, 0, 128));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 128));
        jLabel1.setText("Welcome!");

        registerbutton.setBackground(new java.awt.Color(0, 0, 128));
        registerbutton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        registerbutton.setForeground(new java.awt.Color(255, 255, 255));
        registerbutton.setText("Register");

        loginbutton.setBackground(new java.awt.Color(0, 0, 128));
        loginbutton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        loginbutton.setForeground(new java.awt.Color(255, 255, 255));
        loginbutton.setText("Login");

        javax.swing.GroupLayout openingdialogLayout = new javax.swing.GroupLayout(openingdialog.getContentPane());
        openingdialog.getContentPane().setLayout(openingdialogLayout);
        openingdialogLayout.setHorizontalGroup(
            openingdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(openingdialogLayout.createSequentialGroup()
                .addGroup(openingdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(openingdialogLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(openingdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(registerbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(openingdialogLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel1)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        openingdialogLayout.setVerticalGroup(
            openingdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(openingdialogLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loginbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(registerbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel2.setText("Login");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("Username:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setText("Password:");

        password1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        username1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        loginconfirm.setBackground(new java.awt.Color(0, 0, 0));
        loginconfirm.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        loginconfirm.setForeground(new java.awt.Color(255, 255, 255));
        loginconfirm.setText("Confirm ");

        javax.swing.GroupLayout logindialogLayout = new javax.swing.GroupLayout(logindialog.getContentPane());
        logindialog.getContentPane().setLayout(logindialogLayout);
        logindialogLayout.setHorizontalGroup(
            logindialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logindialogLayout.createSequentialGroup()
                .addGroup(logindialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(logindialogLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(logindialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logindialogLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(logindialogLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)))
                        .addGroup(logindialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(password1, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(username1)))
                    .addGroup(logindialogLayout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel2)))
                .addGap(73, 73, 73))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logindialogLayout.createSequentialGroup()
                .addComponent(loginconfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166))
        );
        logindialogLayout.setVerticalGroup(
            logindialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logindialogLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(48, 48, 48)
                .addGroup(logindialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(username1))
                .addGap(18, 18, 18)
                .addGroup(logindialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(loginconfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel5.setText("Register");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setText("Username:");

        username2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel7.setText("Password:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel8.setText("Retype Password:");

        registerconfirm.setBackground(new java.awt.Color(0, 0, 0));
        registerconfirm.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        registerconfirm.setForeground(new java.awt.Color(255, 255, 255));
        registerconfirm.setText("Confirm");

        password2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        password3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        javax.swing.GroupLayout registerdialogLayout = new javax.swing.GroupLayout(registerdialog.getContentPane());
        registerdialog.getContentPane().setLayout(registerdialogLayout);
        registerdialogLayout.setHorizontalGroup(
            registerdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerdialogLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(registerdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerdialogLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(username2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerdialogLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(password2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerdialogLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(password3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52))
            .addGroup(registerdialogLayout.createSequentialGroup()
                .addGroup(registerdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerdialogLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel5))
                    .addGroup(registerdialogLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(registerconfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        registerdialogLayout.setVerticalGroup(
            registerdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerdialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(25, 25, 25)
                .addGroup(registerdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registerdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(password2)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(registerdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password3, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(registerconfirm, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Choose Difficulty");

        easy.setBackground(new java.awt.Color(255, 255, 255));
        easy.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        easy.setText("Easy");

        medium.setBackground(new java.awt.Color(255, 255, 255));
        medium.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        medium.setText("Medium");

        hard.setBackground(new java.awt.Color(255, 255, 255));
        hard.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        hard.setText("Hard");

        javax.swing.GroupLayout difficultydialogLayout = new javax.swing.GroupLayout(difficultydialog.getContentPane());
        difficultydialog.getContentPane().setLayout(difficultydialogLayout);
        difficultydialogLayout.setHorizontalGroup(
            difficultydialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
            .addComponent(easy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(medium, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(hard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        difficultydialogLayout.setVerticalGroup(
            difficultydialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(difficultydialogLayout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(easy, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(medium, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hard, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hangman");
        setBackground(new java.awt.Color(0, 0, 0));

        jTabbedPane2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jPanel1.setLayout(new java.awt.BorderLayout());

        output.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        output.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        output.setText("jTextField5");
        jPanel1.add(output, java.awt.BorderLayout.PAGE_END);

        newgamebutton.setBackground(new java.awt.Color(0, 0, 128));
        newgamebutton.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        newgamebutton.setForeground(new java.awt.Color(255, 255, 255));
        newgamebutton.setText("New Game  ");
        jPanel1.add(newgamebutton, java.awt.BorderLayout.LINE_START);

        selectdifficultybutton.setBackground(new java.awt.Color(0, 0, 128));
        selectdifficultybutton.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        selectdifficultybutton.setForeground(new java.awt.Color(255, 255, 255));
        selectdifficultybutton.setText("Select Difficulty");
        jPanel1.add(selectdifficultybutton, java.awt.BorderLayout.LINE_END);

        winlosslabel.setBackground(new java.awt.Color(255, 255, 255));
        winlosslabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        winlosslabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        winlosslabel.setText("jLabel9");
        jPanel1.add(winlosslabel, java.awt.BorderLayout.PAGE_START);

        drawingpanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout drawingpanelLayout = new javax.swing.GroupLayout(drawingpanel);
        drawingpanel.setLayout(drawingpanelLayout);
        drawingpanelLayout.setHorizontalGroup(
            drawingpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
        );
        drawingpanelLayout.setVerticalGroup(
            drawingpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        jPanel1.add(drawingpanel, java.awt.BorderLayout.CENTER);

        jTabbedPane2.addTab("Hangman!", jPanel1);

        userinfo.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel10.setText("Username:");
        jLabel10.setToolTipText("");

        label1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        label1.setText("Username:");
        label1.setToolTipText("");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel12.setText("Wins:");
        jLabel12.setToolTipText("");

        label2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        label2.setText("Wins:");
        label2.setToolTipText("");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel14.setText("Losses:");
        jLabel14.setToolTipText("");

        label3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        label3.setText("Losses:");
        label3.setToolTipText("");

        deleteAccountButton.setBackground(new java.awt.Color(255, 0, 0));
        deleteAccountButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        deleteAccountButton.setText("Delete Account");

        javax.swing.GroupLayout userinfoLayout = new javax.swing.GroupLayout(userinfo);
        userinfo.setLayout(userinfoLayout);
        userinfoLayout.setHorizontalGroup(
            userinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userinfoLayout.createSequentialGroup()
                .addContainerGap(158, Short.MAX_VALUE)
                .addGroup(userinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userinfoLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(userinfoLayout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(userinfoLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(135, 135, 135))
            .addGroup(userinfoLayout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(deleteAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        userinfoLayout.setVerticalGroup(
            userinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userinfoLayout.createSequentialGroup()
                .addGroup(userinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userinfoLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userinfoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(deleteAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        jTabbedPane2.addTab("User", userinfo);

        letterpanel.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout letterpanelLayout = new javax.swing.GroupLayout(letterpanel);
        letterpanel.setLayout(letterpanelLayout);
        letterpanelLayout.setHorizontalGroup(
            letterpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        letterpanelLayout.setVerticalGroup(
            letterpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 152, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
            .addComponent(letterpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(letterpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }
    
    public void addLoginAL(ActionListener a)
    {
        loginbutton.addActionListener(a);
    }
    
    public void addRegisterAL(ActionListener a)
    {
        registerbutton.addActionListener(a);
    }
    
    public void addConfirmAL(ActionListener a)
    {
        registerconfirm.addActionListener(a);
        loginconfirm.addActionListener(a);
    }
    
    public void addDeleteAL(ActionListener a)
    {
        deleteAccountButton.addActionListener(a);
    }
    
    public void register()
    {
        openingdialog.setVisible(false);
        registerdialog.setTitle("Register");
        registerdialog.setLocationRelativeTo(null);
        registerdialog.pack();
        registerdialog.setVisible(true);
    }
    
    public void login()
    {
        openingdialog.setVisible(false);
        logindialog.setTitle("Login");
        logindialog.setLocationRelativeTo(null);
        logindialog.pack();
        logindialog.setVisible(true);
    }
    
    public void chooseDifficulty()
    {
        difficultydialog.setTitle("Difficulty");
        difficultydialog.setLocationRelativeTo(null);
        difficultydialog.pack();
        difficultydialog.setVisible(true);
    }
    
    public void addDifficultyAL(ActionListener a)
    {
        easy.addActionListener(a);
        medium.addActionListener(a);
        hard.addActionListener(a);
    }
    
    public void saveLogin()
    {
        username = username1.getText();
        password = String.valueOf(password1.getPassword());
    }
    
    public void saveRegister()
    {
        username = username2.getText();
        password = String.valueOf(password2.getPassword());
        password22 = String.valueOf(password3.getPassword());
    }
    
    public String getUsername()
    {
        return username;
    }
    
    public String getPassword1()
    {
        return password;
    }
    
    public String getPassword2()
    {
        return password22;
    }
    
    public void continue1()
    {
        logindialog.setVisible(false);
    }
    
    public void continue2()
    {
        registerdialog.setVisible(false);
    }
    
    public void mismatch()
    {
        JOptionPane.showMessageDialog(null, "Username or password is wrong");
    }
    
    public void mismatch2()
    {
        JOptionPane.showMessageDialog(null, "Passwords don't match");
    }
    
    public void display()
    {
        difficultydialog.setVisible(false);
        jTabbedPane2.setVisible(true);
        letterpanel.setVisible(true);
    }

    public void genLetters()
    {
        char c = 'A';
        for(int i=0; i<26; i++)
        {
            letterbuttons[i] = new JButton(Character.toString(c));
            c++;
        }
    }
    
    
    public void addLettersAL(ActionListener a)
    {
        for(int i=0; i<26; i++)
        {
            letterbuttons[i].addActionListener(a);
        }
    }
    
    public void addLetters()
    {
        for(int i=0; i<26; i++)
        {
            letterbuttons[i].setPreferredSize(new Dimension (30,30));
            letterbuttons[i].setBackground(new Color(50,50,150));
            letterbuttons[i].setForeground(new Color(0,0,255));
            letterpanel.add(letterbuttons[i]);
        }
    }
    
    
    public void addNewGameAL(ActionListener a)
    {
        newgamebutton.addActionListener(a);
    }
    
    public void addSdAL(ActionListener a)
    {
        selectdifficultybutton.addActionListener(a);
    }
    
    public void setUserTab(String u, int w, int l)
    {
        label1.setText(u);
        label2.setText(Integer.toString(w));
        label3.setText(Integer.toString(l));
    }
    
    public void disableButton(int i)
    {
        letterbuttons[i].setEnabled(false);
    }
    
    public void enableButtons()
    {
        for(int i=0; i<26; i++)
        {
            letterbuttons[i].setEnabled(true);
        }
    }
    
    public void setWinLoss(int win, int loss, String d)
    {
        winlosslabel.setText("WINS: " + win + " LOSS: " + loss + " Difficulty: " + d);
    }
    
    public void updateOutput(String s)
    {
        output.setText(s);
    }
    
    @Override
    public void paint(Graphics g) 
    {
        super.paint(g);
    }
    
    
    public void draw(int counter) 
    {
        gfx = (Graphics2D) drawingpanel.getGraphics();
        switch(counter)
        {
            case 0: gfx.drawLine(207,50,207,80);
                    gfx.drawLine(207, 50, 300, 50);
                    gfx.drawLine(300,50,300,210);
                    gfx.drawLine(255,210,340,210); 
            break;
            case 1: gfx.drawOval(187,80,40,40);      
            break;
            case 2: gfx.drawLine(207,120,207,190);
            break;
            case 3: gfx.drawLine(207, 130, 190, 137);
            break;
            case 4: gfx.drawLine(207, 130, 224, 137);
            break;
            case 5: gfx.drawLine(207,190,190,197);
            break;
            case 6: gfx.drawLine(207,190, 224,197);
            break;
        }
    }
    
    public void loser(String word)
    {
        JOptionPane.showMessageDialog(null, "Game Over! The word was "+word);
        viewreset();
    }
    
    public void winner()
    {
        JOptionPane.showMessageDialog(null, "Congratulations! You win!");
        viewreset();
    }
 
    public void viewreset()
    {
        enableButtons();
        repaint();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteAccountButton;
    private javax.swing.JDialog difficultydialog;
    private javax.swing.JPanel drawingpanel;
    private javax.swing.JButton easy;
    private javax.swing.JButton hard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JPanel letterpanel;
    private javax.swing.JButton loginbutton;
    private javax.swing.JButton loginconfirm;
    private javax.swing.JDialog logindialog;
    private javax.swing.JButton medium;
    private javax.swing.JButton newgamebutton;
    private javax.swing.JDialog openingdialog;
    private javax.swing.JTextField output;
    private javax.swing.JPasswordField password1;
    private javax.swing.JPasswordField password2;
    private javax.swing.JPasswordField password3;
    private javax.swing.JButton registerbutton;
    private javax.swing.JButton registerconfirm;
    private javax.swing.JDialog registerdialog;
    private javax.swing.JButton selectdifficultybutton;
    private javax.swing.JPanel userinfo;
    private javax.swing.JTextField username1;
    private javax.swing.JTextField username2;
    private javax.swing.JLabel winlosslabel;
    // End of variables declaration//GEN-END:variables
}
